In [104]:
### Dependencies and Configuration ###

#from config import password2
#from config import pw2
from sqlalchemy import create_engine

import pandas as pd
import numpy as np
import matplotlib 
#import pyplot as plt

In [105]:
#### IMPORT DATA #####
# Using panda red_excel to import the data from the excel file

EXCEL_PATH = 'data/ATLAS/FoodEnvironmentAtlas.xls'
VARIABLE_PATH = 'data/ATLAS/variables.csv'


# Import entire excel files as dataframes

global_dict = pd.read_excel(EXCEL_PATH,
sheet_name=['ACCESS', 'STORES', 'RESTAURANTS', 'ASSISTANCE', 'INSECURITY', 'LOCAL', 'HEALTH', 'SOCIOECONOMIC'])


#global_dict

In [106]:
## CLEANING DATA ##
### LISTS OF COLUMNS I WANT FROM EACH SHEET ####

ACCESS_LIST = ['FIPS',
'PCT_LACCESS_POP10',
'PCT_LACCESS_POP15',
'PCT_LACCESS_LOWI10',
'PCT_LACCESS_LOWI15',
'PCT_LACCESS_HHNV10',
'PCT_LACCESS_HHNV15',
'PCT_LACCESS_SNAP15']

STORES_LIST = [
'GROCPTH11',
'GROCPTH16',
'SUPERCPTH11',
'SUPERCPTH16',
'CONVSPTH11',
'CONVSPTH16',
'SNAPSPTH12',
'SNAPSPTH17',
'WICSPTH11',
'WICSPTH16']

RESTAURANTS_LIST = ['FFRPTH11',
'FFRPTH16',
'FSRPTH11',
'FSRPTH16',
'PC_FFRSALES07',
'PC_FFRSALES12',
'PC_FSRSALES07',
'PC_FSRSALES12']

ASSISTANCE_LIST = [
'REDEMP_SNAPS12',
'REDEMP_SNAPS17',
'PCT_SNAP12',
'PCT_SNAP17',
'PC_SNAPBEN12',
'PC_SNAPBEN17',
'SNAP_PART_RATE11',
'SNAP_PART_RATE16',
'PC_WIC_REDEMP11',
'PC_WIC_REDEMP16',
'REDEMP_WICS11',
'REDEMP_WICS16',
'PCT_WIC12',
'PCT_WIC17',
'PCT_WICINFANTCHILD14',
'PCT_WICINFANTCHILD16',
'FOOD_BANKS18']

INSECURITY_LIST = [
'FOODINSEC_12_14',
'FOODINSEC_15_17',
'VLFOODSEC_12_14',
'VLFOODSEC_15_17']

LOCAL_LIST = [
'FMRKTPTH13',
'FMRKTPTH18',
'FOODHUB18']

HEALTH_LIST = [
'PCT_DIABETES_ADULTS08',
'PCT_DIABETES_ADULTS13',
'PCT_OBESE_ADULTS12',
'PCT_OBESE_ADULTS17',
'PCT_HSPA17',
'RECFACPTH11',
'RECFACPTH16']

SOCIOECONOMIC_LIST = [
'MEDHHINC15',
'POVRATE15',
'PERPOV10',
'CHILDPOVRATE15',
'PERCHLDPOV10',
'METRO13']


GLOBAL_LIST = ACCESS_LIST + STORES_LIST + RESTAURANTS_LIST + ASSISTANCE_LIST + INSECURITY_LIST + LOCAL_LIST + HEALTH_LIST + SOCIOECONOMIC_LIST

GLOBAL_LIST

['FIPS',
 'PCT_LACCESS_POP10',
 'PCT_LACCESS_POP15',
 'PCT_LACCESS_LOWI10',
 'PCT_LACCESS_LOWI15',
 'PCT_LACCESS_HHNV10',
 'PCT_LACCESS_HHNV15',
 'PCT_LACCESS_SNAP15',
 'GROCPTH11',
 'GROCPTH16',
 'SUPERCPTH11',
 'SUPERCPTH16',
 'CONVSPTH11',
 'CONVSPTH16',
 'SNAPSPTH12',
 'SNAPSPTH17',
 'WICSPTH11',
 'WICSPTH16',
 'FFRPTH11',
 'FFRPTH16',
 'FSRPTH11',
 'FSRPTH16',
 'PC_FFRSALES07',
 'PC_FFRSALES12',
 'PC_FSRSALES07',
 'PC_FSRSALES12',
 'REDEMP_SNAPS12',
 'REDEMP_SNAPS17',
 'PCT_SNAP12',
 'PCT_SNAP17',
 'PC_SNAPBEN12',
 'PC_SNAPBEN17',
 'SNAP_PART_RATE11',
 'SNAP_PART_RATE16',
 'PC_WIC_REDEMP11',
 'PC_WIC_REDEMP16',
 'REDEMP_WICS11',
 'REDEMP_WICS16',
 'PCT_WIC12',
 'PCT_WIC17',
 'PCT_WICINFANTCHILD14',
 'PCT_WICINFANTCHILD16',
 'FOOD_BANKS18',
 'FOODINSEC_12_14',
 'FOODINSEC_15_17',
 'VLFOODSEC_12_14',
 'VLFOODSEC_15_17',
 'FMRKTPTH13',
 'FMRKTPTH18',
 'FOODHUB18',
 'PCT_DIABETES_ADULTS08',
 'PCT_DIABETES_ADULTS13',
 'PCT_OBESE_ADULTS12',
 'PCT_OBESE_ADULTS17',
 'PCT_HSPA17',
 'RECFACPTH11',
 'RECFACPTH16',
 'MEDHHINC15',
 'POVRATE15',
 'PERPOV10',
 'CHILDPOVRATE15',
 'PERCHLDPOV10',
 'METRO13']

In [126]:
#### GET THE VARIABLE INFORMATION TO CREATE A TABLE WITH DESCRIPTIONS #####

variables_df = pd.read_csv(VARIABLE_PATH)
variables_df

definitions_df = variables_df.loc[variables_df['Variable Code'].isin(GLOBAL_LIST)]
definitions_df

definitions_clean_df = definitions_df.drop(['Category Name', 'Subcategory Name', 'Geography'], axis=1)
definitions_clean_df
### WRITE VARIABLE DEFINITIONS TO A CSV FILE ###

definitions_clean_df.to_csv('data/ATLAS/definitions.csv')

In [114]:
### USE THE LISTS ABOVE TO CREATE DATAFRAMES FROM EACH SHEET ###

access_df = global_dict['ACCESS'][ACCESS_LIST]
store_df = global_dict['STORES'][STORES_LIST]
restaurants_df = global_dict['RESTAURANTS'][RESTAURANTS_LIST]
assistance_df = global_dict['ASSISTANCE'][ASSISTANCE_LIST]
insecurity_df = global_dict['INSECURITY'][INSECURITY_LIST]
local_df = global_dict['LOCAL'][LOCAL_LIST]
health_df = global_dict['HEALTH'][HEALTH_LIST]
socioeconomic_df = global_dict['SOCIOECONOMIC'][SOCIOECONOMIC_LIST]

#access_df.head()

In [121]:
#### MERGE ALL DATAFRAMES INTO ONE DATAFRAME #####

DATAFRAME_LIST = ['access_df', 'store_df', 'restaurants_df', 'assistance_df', 'insecurity_df', 'local_df', 'health_df', 'socioeconomic_df']

proposed_merged_df = pd.concat([access_df, store_df, restaurants_df, assistance_df, insecurity_df, local_df, health_df, socioeconomic_df], axis=1)

proposed_merged_df.shape

proposed_merged_df.head()

proposed_merged_df.dtypes

FIPS                  float64
PCT_LACCESS_POP10     float64
PCT_LACCESS_POP15     float64
PCT_LACCESS_LOWI10    float64
PCT_LACCESS_LOWI15    float64
                       ...
POVRATE15             float64
PERPOV10              float64
CHILDPOVRATE15        float64
PERCHLDPOV10          float64
METRO13               float64
Length: 63, dtype: object

In [116]:
### get a list of datatypes for the merged list

merged_datatypes = proposed_merged_df.dtypes

merged_datatypes

FIPS                  float64
PCT_LACCESS_POP10     float64
PCT_LACCESS_POP15     float64
PCT_LACCESS_LOWI10    float64
PCT_LACCESS_LOWI15    float64
                       ...
POVRATE15             float64
PERPOV10              float64
CHILDPOVRATE15        float64
PERCHLDPOV10          float64
METRO13               float64
Length: 63, dtype: object

In [117]:

# Output the datatypes to a txt file

pd.DataFrame.to_csv(merged_datatypes, '../Local_resources//merged_datatypes.txt',sep=',', na_rep='.', index=True)

In [118]:
### OUTPUT THE MERGED DATAFRAME TO A CSV FILE ###

proposed_merged_df.to_csv('data/ATLAS/FoodEnvironmentAtlas_proposed.csv')

In [128]:

proposed_merged_df.hist

proposed_merged_df.describe()

,FIPS,PCT_LACCESS_POP10,PCT_LACCESS_POP15,PCT_LACCESS_LOWI10,PCT_LACCESS_LOWI15,PCT_LACCESS_HHNV10,PCT_LACCESS_HHNV15,PCT_LACCESS_SNAP15,GROCPTH11,GROCPTH16,...,PCT_OBESE_ADULTS17,PCT_HSPA17,RECFACPTH11,RECFACPTH16,MEDHHINC15,POVRATE15,PERPOV10,CHILDPOVRATE15,PERCHLDPOV10,METRO13
count,3143.000000,3143.000000,3124.000000,3143.000000,3123.000000,3143.000000,3140.000000,3123.000000,3143.000000,3143.000000,...,3143.000000,2383.000000,3143.000000,3143.000000,3139.000000,3139.000000,3143.000000,3139.000000,3143.000000,3143.000000
mean,30390.411709,23.559330,23.084470,8.374953,8.651256,3.154496,3.289225,2.917896,0.258088,0.243835,...,31.862965,24.620520,0.071337,0.070300,48611.206117,16.260975,0.112313,23.238738,0.225262,0.371301
std,15164.717720,20.250176,19.602745,8.214988,8.368703,3.207105,3.213497,3.160642,0.226151,0.216536,...,3.329267,2.822971,0.073805,0.075829,12351.988288,6.442319,0.315801,9.364172,0.417822,0.483230
min,1001.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,22.600000,13.400000,0.000000,0.000000,22894.000000,3.400000,0.000000,3.300000,0.000000,0.000000
25%,18178.000000,10.847099,10.927326,3.442171,3.625438,1.609832,1.683158,1.132022,0.145277,0.132983,...,30.100000,22.400000,0.000000,0.000000,40438.000000,11.500000,0.000000,16.250000,0.000000,0.000000
50%,29177.000000,19.685956,19.200682,6.150772,6.508531,2.572299,2.672985,2.128783,0.198373,0.186116,...,32.400000,24.700000,0.064726,0.061983,46807.000000,15.200000,0.000000,22.300000,0.000000,0.000000
75%,45082.000000,29.581054,28.862231,10.324935,10.679796,3.806324,4.036167,3.668171,0.290565,0.279887,...,33.800000,26.500000,0.107117,0.108090,54164.000000,19.700000,0.000000,29.100000,0.000000,1.000000
max,56045.000000,100.000001,100.000001,72.274456,71.844209,68.470405,60.602394,37.254488,3.048780,3.267974,...,38.100000,30.800000,0.628141,1.053741,125900.000000,47.400000,1.000000,61.600000,1.000000,1.000000